added more info to properties file

diff --git a/.github/workflows/quality_checks.yml b/.github/workflows/quality_checks.yml
--- a/.github/workflows/quality_checks.yml
+++ b/.github/workflows/quality_checks.yml
@@ -51,7 +51,7 @@ jobs:
       - name: check licences
         run: make check-licences 
 
-      - name: Test and Build
+      - name: Run tests, generate coverage, and build
         run: make build
 
       - uses: actions/upload-artifact@v4
@@ -72,9 +72,6 @@ jobs:
       #   env:
       #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-      - name: run unit tests
-        run: make test 
-        
       # - name: Run tests with debug output
       #   run: mvn clean test jacoco:report -X
 
@@ -97,6 +94,9 @@ jobs:
       
       # - name: Check test results
       #   run: cat target/surefire-reports/*.txt || echo "No test results found"
+
+      - name: Check Maven test output
+        run: cat target/maven-test-output.txt || echo "Maven test output not found"
       
       - name: Check Maven build output
         run: cat target/maven-build-output.txt || echo "Maven build output not found"
